### ISSUE TITLE
Small clarifications in the .h file

### ISSUE THREAD

**Issue by pac-work** [vsf-tv/gccg-api#24]
- The sgl_array in the code in GccgMediaElements does not need to be **, but just *? Or does it?
- The code misses some notes about thread safety requirements of individual functions.
   Examples:
   - Is GccgRxFreeBuffer supposed to be thread safe?
   - Can I receive second RX callback if my code is still handling the previous one in the multithreaded initialization case?

**Comment by mhhen** [comment]
* sgl_array in [GccgMediaElements](https://github.com/vsf-tv/gccg-api/blob/0d83d0bcca96dee794a673023bc263d20332253d/gccg_transport_api.h#L109) is declared using ** since it is as pointer to an array of **GccgSgList** pointers.
* Code will be updated to include comments concerning thread-safety. Basically, all APIs are thread-safe.

**Comment by pac-work** [comment]
Thanks for explanations, I was kind of blindly assuming that the `GccgSgList` instances would be in a continuous memory block, but now I see that the chosen way of indirection allows implementations to not have them continuously, which I guess some of the implementations may benefit from. So oversight on my side.

Thanks for clarifying the other things in the code.
